(()=>{
'use strict';
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number.isFinite(+n)?+n:0);
const clamp=(v,min,max)=>Math.min(max,Math.max(min,Number(v)||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const getJSON=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const setJSON=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const pricingDefaults={fullJunk:500,fullEstate:575,fullConstruction:625,fullYard:450,fullAppliance:500,mileRate:1.10,laborRate:40,margin:15,minimum:95,roundTo:25};
let photos=[], photoDataUrls=[], visionResult=null, model=null, modelPromise=null, currentJobId=null, finalConfirmed=false;

const objectRules={
 'couch':{low:.14,high:.22,weight:[80,180],labor:2},'chair':{low:.03,high:.06,weight:[15,60],labor:1},'bed':{low:.10,high:.18,weight:[50,160],labor:2},'dining table':{low:.08,high:.14,weight:[40,130],labor:2},'bench':{low:.04,high:.08,weight:[20,90],labor:1},'refrigerator':{low:.10,high:.16,weight:[180,350],labor:3,special:25},'microwave':{low:.015,high:.03,weight:[20,55],labor:1},'oven':{low:.08,high:.12,weight:[120,250],labor:3,special:20},'toaster':{low:.005,high:.012,weight:[3,10],labor:0},'tv':{low:.025,high:.05,weight:[10,70],labor:1},'laptop':{low:.003,high:.008,weight:[2,8],labor:0},'book':{low:.003,high:.01,weight:[1,8],labor:0},'suitcase':{low:.025,high:.06,weight:[8,45],labor:1},'backpack':{low:.012,high:.03,weight:[2,25],labor:0},'bicycle':{low:.035,high:.07,weight:[15,45],labor:1},'motorcycle':{low:.08,high:.14,weight:[220,700],labor:3,special:35},'potted plant':{low:.02,high:.05,weight:[5,45],labor:1},'bottle':{low:.002,high:.006,weight:[1,5],labor:0},'person':{low:0,high:0,weight:[0,0],labor:0}
};
function pricing(){const out={};Object.keys(pricingDefaults).forEach(k=>out[k]=clamp($(k).value,0,k==='margin'?200:100000));return out}
function savePricing(){setJSON('imPricingV3',pricing());calculateEstimate();calculateFinal()}
function loadPricing(){const p=getJSON('imPricingV3',pricingDefaults);Object.keys(pricingDefaults).forEach(k=>$(k).value=p[k]??pricingDefaults[k])}
function baseRate(jobType=$('jobType').value){const p=pricing();return({junk:p.fullJunk,estate:p.fullEstate,construction:p.fullConstruction,yard:p.fullYard,appliance:p.fullAppliance}[jobType]||p.fullJunk)}
function calcQuote(pct,miles,dump,hours,special,jobType=$('jobType').value){const p=pricing(),load=baseRate(jobType)*clamp(pct,0,4),travel=clamp(miles,0,5000)*p.mileRate,labor=clamp(hours,0,500)*p.laborRate,internal=load+travel+labor+clamp(dump,0,50000)+clamp(special,0,50000),raw=Math.max(p.minimum,internal*(1+p.margin/100)),step=Math.max(1,p.roundTo),quote=Math.ceil(raw/step)*step;return{load,travel,labor,dump:+dump||0,special:+special||0,internal,quote}}
function normalizedLoads(){let lo=clamp($('loadLow').value,.05,4),hi=clamp($('loadHigh').value,.05,4);if(lo>hi)[lo,hi]=[hi,lo];return[lo,hi]}
function calculateEstimate(){const[lo,hi]=normalizedLoads(),m=clamp($('miles').value,0,5000),d=clamp($('dumpFee').value,0,50000),s=clamp($('specialFee').value,0,50000),h1=clamp($('laborHoursLow').value,0,500),h2=Math.max(h1,clamp($('laborHoursHigh').value,0,500)),a=calcQuote(lo,m,d,h1,s),b=calcQuote(hi,m,d,h2,s);$('summaryLoad').textContent=`${Math.round(lo*100)}–${Math.round(hi*100)}%`;$('summaryMiles').textContent=`${Math.round(m)} mi round trip`;$('summaryDump').textContent=money(d);$('summaryLabor').textContent=`${h1}–${h2} hr`;$('estimateRange').textContent=`${money(a.quote)}–${money(b.quote)}`;$('internalLow').textContent=money(a.internal);$('internalHigh').textContent=money(b.internal);$('marginView').textContent=`${pricing().margin}%`;return{lowPct:lo,highPct:hi,miles:m,dump:d,special:s,hoursLow:h1,hoursHigh:h2,low:a,high:b}}
function syncOnsite(){const e=calculateEstimate();$('finalLoad').value=nearestLoad((e.lowPct+e.highPct)/2);$('finalMiles').value=e.miles;$('finalDump').value=e.dump;$('finalLaborHours').value=((e.hoursLow+e.hoursHigh)/2).toFixed(2).replace(/\.00$/,'');$('finalSpecial').value=e.special;$('finalOverride').value='';$('onsiteNotes').value='';finalConfirmed=false;$('finalBadge').classList.add('hidden');calculateFinal()}
function calculateFinal(){const pct=clamp($('finalLoad').value,.05,4),m=clamp($('finalMiles').value,0,5000),d=clamp($('finalDump').value,0,50000),h=clamp($('finalLaborHours').value,0,500),s=clamp($('finalSpecial').value,0,50000),c=calcQuote(pct,m,d,h,s),override=Number($('finalOverride').value),q=Number.isFinite(override)&&override>0?override:c.quote;$('finalLoadView').textContent=`${Math.round(pct*100)}%`;$('finalMilesView').textContent=`${Math.round(m)} mi`;$('finalDumpView').textContent=money(d);$('finalLaborView').textContent=`${h} hr`;$('finalQuote').textContent=money(q);return{pct,miles:m,dump:d,hours:h,special:s,calculated:c.quote,quote:q,internal:c.internal}}
function nearestLoad(v){const vals=[.10,.15,.25,.35,.5,.65,.75,1,1.25,1.5,2];return String(vals.reduce((a,b)=>Math.abs(b-v)<Math.abs(a-v)?b:a,vals[0]))}
function nearestLowHigh(low,high){const vals=[.10,.15,.25,.35,.5,.65,.75,1,1.25,1.5,2];const near=v=>vals.reduce((a,b)=>Math.abs(b-v)<Math.abs(a-v)?b:a,vals[0]);let a=near(low),b=near(high);if(a>b)[a,b]=[b,a];if(a===b){const i=vals.indexOf(b);if(i<vals.length-1)b=vals[i+1]}return[a,b]}

async function readFile(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
async function loadModel(){if(model)return model;if(modelPromise)return modelPromise;if(!window.cocoSsd)throw new Error('Photo model did not load. Check your internet connection and try again.');$('modelStatus').className='status work';$('modelStatus').textContent='Loading free on-device photo model…';modelPromise=window.cocoSsd.load({base:'lite_mobilenet_v2'}).then(m=>{model=m;$('modelStatus').className='status good';$('modelStatus').textContent='On-device photo model loaded. No API fees.';return m}).catch(e=>{$('modelStatus').className='status bad';$('modelStatus').textContent='Could not load the photo model.';modelPromise=null;throw e});return modelPromise}
function setVisionStatus(t,kind=''){$('visionStatus').className='status '+kind;$('visionStatus').innerHTML=t}
async function analyzePhotos(){if(!photos.length){setVisionStatus('Take or upload at least one photo first.','bad');return}$('analyzeBtn').disabled=true;setVisionStatus('Loading the on-device model and analyzing your photos…','work');try{const m=await loadModel();let photoResults=[];for(let i=0;i<photos.length;i++){setVisionStatus(`Analyzing photo ${i+1} of ${photos.length}…`,'work');const img=await imageFromDataUrl(photoDataUrls[i]);const preds=await m.detect(img,30,.35);photoResults.push({preds,width:img.naturalWidth||img.width,height:img.naturalHeight||img.height})}visionResult=buildVisionEstimate(photoResults,$('photoMode').value);applyVision(visionResult);setVisionStatus('Photo analysis complete. Review the range before sending it to the customer.','good')}catch(e){console.error(e);setVisionStatus(`${esc(e.message||'Photo analysis failed.')} You can still enter the load range manually.`,'bad')}finally{$('analyzeBtn').disabled=false}}
function imageFromDataUrl(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=src})}
function buildVisionEstimate(results,mode){const per=[];let confs=[],allItems=[];for(const r of results){let low=0,high=0,wLow=0,wHigh=0,labor=0,special=0,coverage=0,items=[];for(const p of r.preds){if(p.class==='person')continue;const rule=objectRules[p.class];if(!rule)continue;const area=(p.bbox[2]*p.bbox[3])/(Math.max(1,r.width*r.height));const areaFactor=Math.max(.65,Math.min(1.45,Math.sqrt(area/.08)||1));low+=rule.low*areaFactor;high+=rule.high*areaFactor;wLow+=rule.weight[0];wHigh+=rule.weight[1];labor+=rule.labor;special+=rule.special||0;coverage+=area;items.push(p.class);allItems.push(p.class);confs.push(p.score)}
 const unknownBoost=Math.min(.18,Math.max(0,coverage-.35)*.25);if(items.length===0){low=.15;high=.35;wLow=80;wHigh=500}else{low+=unknownBoost;high+=unknownBoost*1.5}per.push({low:Math.max(.08,low),high:Math.max(.15,high),wLow,wHigh,labor,special,items})}
 let low,high,wLow,wHigh,labor,special;if(mode==='different'){low=per.reduce((s,x)=>s+x.low,0);high=per.reduce((s,x)=>s+x.high,0);wLow=per.reduce((s,x)=>s+x.wLow,0);wHigh=per.reduce((s,x)=>s+x.wHigh,0);labor=per.reduce((s,x)=>s+x.labor,0);special=per.reduce((s,x)=>s+x.special,0)}else{low=Math.max(...per.map(x=>x.low));high=Math.max(...per.map(x=>x.high));wLow=Math.max(...per.map(x=>x.wLow));wHigh=Math.max(...per.map(x=>x.wHigh));labor=Math.max(...per.map(x=>x.labor));special=Math.max(...per.map(x=>x.special))}
 low=Math.min(2,Math.max(.10,low));high=Math.min(2,Math.max(low+.08,high));const confidence=confs.length?confs.reduce((a,b)=>a+b,0)/confs.length:.35;const uniq=[...new Set(allItems)];let difficulty=labor>=7||wHigh>1200?'Heavy':labor>=3||wHigh>500?'Medium':'Light';const hoursLow=difficulty==='Heavy'?2:difficulty==='Medium'?1:.5,hoursHigh=difficulty==='Heavy'?3.5:difficulty==='Medium'?2:1;return{low,high,wLow:Math.max(50,wLow),wHigh:Math.max(250,wHigh),difficulty,hoursLow,hoursHigh,special:Math.min(200,special),confidence,items:uniq}}
function applyVision(v){const[a,b]=nearestLowHigh(v.low,v.high);$('loadLow').value=a;$('loadHigh').value=b;$('laborHoursLow').value=v.hoursLow;$('laborHoursHigh').value=v.hoursHigh;if(v.special>$('specialFee').value)$('specialFee').value=v.special;$('analysisLoad').textContent=`${Math.round(a*100)}–${Math.round(b*100)}%`;$('analysisWeight').textContent=`${Math.round(v.wLow/25)*25}–${Math.round(v.wHigh/25)*25} lb`;$('analysisLabor').textContent=v.difficulty;$('analysisConfidence').textContent=`${Math.round(v.confidence*100)}%`;$('detectedItems').innerHTML=v.items.length?v.items.map(x=>`<span class="itemchip">${esc(x)}</span>`).join(''):'<span class="small">No common large objects confidently detected. Review the load range manually.</span>';calculateEstimate()}

function estimateSummary(final=false){const e=calculateEstimate(),f=calculateFinal(),det=visionResult?.items||[];if(final)return`IRON MULE HAULING CO.\nFINAL QUOTE\n\nCustomer: ${$('customerName').value||'Customer'}\nPickup: ${$('address').value||'—'}\nFinal price: ${money(f.quote)}\nVerified load: ${Math.round(f.pct*100)}% of trailer\nTravel: ${Math.round(f.miles)} round-trip miles\nDisposal allowance: ${money(f.dump)}\nLabor: ${f.hours} hr\nSpecial handling: ${money(f.special)}\n\nFinal price confirmed before loading.`;return`IRON MULE HAULING CO.\nPHOTO ESTIMATE\n\nCustomer: ${$('customerName').value||'Customer'}\nPickup: ${$('address').value||'—'}\nEstimated price: ${money(e.low.quote)}–${money(e.high.quote)}\nEstimated load: ${Math.round(e.lowPct*100)}–${Math.round(e.highPct*100)}% of trailer\nTravel: ${Math.round(e.miles)} round-trip miles\nDisposal allowance: ${money(e.dump)}\nEstimated labor: ${e.hoursLow}–${e.hoursHigh} hr\nSpecial handling allowance: ${money(e.special)}${det.length?`\nVisible items detected: ${det.join(', ')}`:''}\n\nPhoto estimate only. Final price is confirmed onsite before loading begins.`}
async function shareText(text,title){if(navigator.share){try{await navigator.share({title,text});return}catch(e){if(e.name==='AbortError')return}}downloadText(text,title.replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.txt')}
function downloadText(text,name){const b=new Blob([text],{type:'text/plain'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function customerReportHTML(){const e=calculateEstimate(),items=visionResult?.items||[],name=esc($('customerName').value||'Customer'),addr=esc($('address').value||'—'),notes=esc($('notes').value||'');const imgs=photoDataUrls.slice(0,3).map(s=>`<img src="${s}" alt="Job photo">`).join('');return`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Iron Mule Estimate</title><style>body{font-family:Arial,sans-serif;max-width:760px;margin:0 auto;padding:28px;color:#222}header{border-bottom:4px solid #b68b2f;padding-bottom:14px;margin-bottom:20px}h1{margin:0;font-size:30px}h2{font-size:18px;margin-top:25px}.gold{color:#916a18}.range{font-size:38px;font-weight:900;color:#916a18}.row{display:flex;justify-content:space-between;gap:20px;border-bottom:1px solid #ddd;padding:10px 0}.muted{color:#666;font-size:13px;line-height:1.5}.photos{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.photos img{width:100%;aspect-ratio:1.25/1;object-fit:cover;border-radius:8px}.box{border:1px solid #ddd;border-radius:10px;padding:14px;margin-top:15px}.footer{margin-top:30px;padding-top:15px;border-top:1px solid #ddd}.print{padding:10px 14px;font-weight:bold}@media print{.print{display:none}}@media(max-width:560px){.photos{grid-template-columns:1fr 1fr}.range{font-size:32px}}</style></head><body><button class="print" onclick="window.print()">Print / Save as PDF</button><header><h1>IRON MULE HAULING CO.</h1><div class="gold"><b>Photo Estimate</b> • You Call. We Haul.</div></header><div><b>Customer:</b> ${name}<br><b>Pickup:</b> ${addr}</div><h2>Estimated Price</h2><div class="range">${money(e.low.quote)}–${money(e.high.quote)}</div><p class="muted">This is a photo-based estimate. The final price is confirmed onsite before loading begins.</p><h2>Why the estimate is in this range</h2><div class="box"><div class="row"><span>Estimated trailer space</span><b>${Math.round(e.lowPct*100)}–${Math.round(e.highPct*100)}%</b></div><div class="row"><span>Round-trip travel</span><b>${Math.round(e.miles)} miles</b></div><div class="row"><span>Disposal allowance</span><b>${money(e.dump)}</b></div><div class="row"><span>Estimated loading time</span><b>${e.hoursLow}–${e.hoursHigh} hr</b></div><div class="row"><span>Special handling allowance</span><b>${money(e.special)}</b></div>${visionResult?`<div class="row"><span>Approx. visible weight</span><b>${Math.round(visionResult.wLow/25)*25}–${Math.round(visionResult.wHigh/25)*25} lb</b></div>`:''}</div>${items.length?`<h2>Visible Items Detected</h2><p>${items.map(esc).join(', ')}</p>`:''}${notes?`<h2>Job Notes</h2><p>${notes}</p>`:''}${imgs?`<h2>Estimate Photos</h2><div class="photos">${imgs}</div>`:''}<div class="footer muted"><b>Important:</b> Photos can hide items, depth, weight, stairs, access issues, or material that requires special disposal. Iron Mule Hauling Co. will confirm the final price onsite before any loading begins.</div></body></html>`}
function openCustomerReport(){const b=new Blob([customerReportHTML()],{type:'text/html'}),u=URL.createObjectURL(b),w=window.open(u,'_blank');if(!w)downloadReport();setTimeout(()=>URL.revokeObjectURL(u),60000)}
function downloadReport(){const b=new Blob([customerReportHTML()],{type:'text/html'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`Iron-Mule-Estimate-${($('customerName').value||'Customer').replace(/[^a-z0-9]+/gi,'-')}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}

function jobData(){return{id:currentJobId||crypto.randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),customerName:$('customerName').value.trim(),customerPhone:$('customerPhone').value.trim(),address:$('address').value.trim(),jobType:$('jobType').value,photoMode:$('photoMode').value,notes:$('notes').value.trim(),estimate:{loadLow:+$('loadLow').value,loadHigh:+$('loadHigh').value,miles:+$('miles').value,dumpFee:+$('dumpFee').value,laborHoursLow:+$('laborHoursLow').value,laborHoursHigh:+$('laborHoursHigh').value,specialFee:+$('specialFee').value,calculated:calculateEstimate()},vision:visionResult,final:finalConfirmed?{...calculateFinal(),notes:$('onsiteNotes').value}:null}}
function saveJob(){const j=jobData(),jobs=getJSON('imJobsV3',[]),i=jobs.findIndex(x=>x.id===j.id);if(i>=0)jobs[i]={...jobs[i],...j,createdAt:jobs[i].createdAt};else jobs.unshift(j);setJSON('imJobsV3',jobs.slice(0,300));currentJobId=j.id;renderJobs();alert('Job saved on this phone.')}
function renderJobs(){const jobs=getJSON('imJobsV3',[]),wrap=$('historyList');if(!jobs.length){wrap.innerHTML='<div class="empty">No saved jobs yet.</div>';return}wrap.innerHTML=jobs.map(j=>{const q=j.final?.quote??j.estimate?.calculated?.high?.quote??0;return`<article class="job" data-id="${esc(j.id)}"><div class="jobtop"><div><div class="jobname">${esc(j.customerName||'Unnamed customer')}</div><div class="jobmeta">${esc(j.address||'No address')} • ${new Date(j.createdAt).toLocaleDateString()}</div></div><div class="jobquote">${money(q)}</div></div><div class="jobmeta">${j.final?'Final quote':'Photo estimate'}${j.final?'':` • ${money(j.estimate.calculated.low.quote)}–${money(j.estimate.calculated.high.quote)}`}</div><div class="jobbuttons"><button data-act="open">Open</button><button data-act="delete" class="danger">Delete</button></div></article>`}).join('')}
function openJob(id){const j=getJSON('imJobsV3',[]).find(x=>x.id===id);if(!j)return;currentJobId=j.id;$('customerName').value=j.customerName||'';$('customerPhone').value=j.customerPhone||'';$('address').value=j.address||'';$('jobType').value=j.jobType||'junk';$('photoMode').value=j.photoMode||'same';$('notes').value=j.notes||'';const e=j.estimate||{};$('loadLow').value=e.loadLow||.25;$('loadHigh').value=e.loadHigh||.5;$('miles').value=e.miles||0;$('dumpFee').value=e.dumpFee||0;$('laborHoursLow').value=e.laborHoursLow||1;$('laborHoursHigh').value=e.laborHoursHigh||1.5;$('specialFee').value=e.specialFee||0;visionResult=j.vision||null;if(visionResult)applyVisionDisplayOnly(visionResult);calculateEstimate();syncOnsite();if(j.final){$('finalLoad').value=nearestLoad(j.final.pct);$('finalMiles').value=j.final.miles;$('finalDump').value=j.final.dump;$('finalLaborHours').value=j.final.hours;$('finalSpecial').value=j.final.special;$('finalOverride').value=j.final.quote;$('onsiteNotes').value=j.final.notes||'';finalConfirmed=true;$('finalBadge').classList.remove('hidden');calculateFinal()}showTab('estimate')}
function applyVisionDisplayOnly(v){$('analysisLoad').textContent=`${Math.round(v.low*100)}–${Math.round(v.high*100)}%`;$('analysisWeight').textContent=`${Math.round(v.wLow/25)*25}–${Math.round(v.wHigh/25)*25} lb`;$('analysisLabor').textContent=v.difficulty;$('analysisConfidence').textContent=`${Math.round(v.confidence*100)}%`;$('detectedItems').innerHTML=(v.items||[]).map(x=>`<span class="itemchip">${esc(x)}</span>`).join('')}
function resetJob(){currentJobId=null;visionResult=null;photos=[];photoDataUrls=[];finalConfirmed=false;$('photos').value='';$('thumbs').innerHTML='';['customerName','customerPhone','address','notes','onsiteNotes','finalOverride'].forEach(id=>$(id).value='');$('jobType').value='junk';$('photoMode').value='same';$('loadLow').value='.25';$('loadHigh').value='.5';$('miles').value='20';$('dumpFee').value='50';$('laborHoursLow').value='1';$('laborHoursHigh').value='1.5';$('specialFee').value='0';$('analysisLoad').textContent='Manual';$('analysisWeight').textContent='Manual';$('analysisLabor').textContent='Manual';$('analysisConfidence').textContent='—';$('detectedItems').innerHTML='';setVisionStatus('Take a photo, then tap <b>Analyze Photos</b>.');$('finalBadge').classList.add('hidden');calculateEstimate();syncOnsite();showTab('estimate')}
function showTab(name){['estimate','onsite','jobs','settings'].forEach(n=>$('tab-'+n).classList.toggle('hidden',n!==name));document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$('stage1').classList.toggle('on',name==='estimate');$('stage2').classList.toggle('on',name==='onsite'&&!finalConfirmed);$('stage3').classList.toggle('on',name==='onsite'&&finalConfirmed);if(name==='jobs')renderJobs();if(name==='onsite'&&!$('finalMiles').value)syncOnsite()}
function exportJobs(){downloadText(JSON.stringify(getJSON('imJobsV3',[]),null,2),'iron-mule-jobs.json')}

['loadLow','loadHigh','miles','dumpFee','laborHoursLow','laborHoursHigh','specialFee','jobType'].forEach(id=>$(id).addEventListener('input',()=>{calculateEstimate();if(!finalConfirmed)syncOnsite()}));['finalLoad','finalMiles','finalDump','finalLaborHours','finalSpecial','finalOverride'].forEach(id=>$(id).addEventListener('input',()=>{finalConfirmed=false;$('finalBadge').classList.add('hidden');calculateFinal()}));Object.keys(pricingDefaults).forEach(id=>$(id).addEventListener('input',savePricing));
$('photos').addEventListener('change',async e=>{photos=[...e.target.files].filter(f=>f.type.startsWith('image/')).slice(0,5);photoDataUrls=[];$('thumbs').innerHTML='';for(const f of photos){const d=await readFile(f);photoDataUrls.push(d);const im=document.createElement('img');im.src=d;im.alt='Job photo';$('thumbs').appendChild(im)}setVisionStatus(photos.length?`${photos.length} photo${photos.length===1?'':'s'} ready for on-device analysis.`:'Take a photo, then tap Analyze Photos.')});
$('analyzeBtn').addEventListener('click',analyzePhotos);$('shareEstimate').addEventListener('click',()=>shareText(estimateSummary(false),'Iron Mule Photo Estimate'));$('customerReport').addEventListener('click',openCustomerReport);$('confirmFinal').addEventListener('click',()=>{finalConfirmed=true;$('finalBadge').classList.remove('hidden');$('stage2').classList.remove('on');$('stage3').classList.add('on');saveJob()});$('shareFinal').addEventListener('click',()=>shareText(estimateSummary(true),'Iron Mule Final Quote'));$('newJob').addEventListener('click',resetJob);$('saveJob').addEventListener('click',saveJob);$('exportJobs').addEventListener('click',exportJobs);$('clearJobs').addEventListener('click',()=>{if(confirm('Delete all saved jobs from this phone?')){localStorage.removeItem('imJobsV3');renderJobs()}});$('resetSettings').addEventListener('click',()=>{Object.entries(pricingDefaults).forEach(([k,v])=>$(k).value=v);savePricing()});document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));$('historyList').addEventListener('click',e=>{const b=e.target.closest('button'),j=e.target.closest('.job');if(!b||!j)return;if(b.dataset.act==='open')openJob(j.dataset.id);if(b.dataset.act==='delete'&&confirm('Delete this job?')){setJSON('imJobsV3',getJSON('imJobsV3',[]).filter(x=>x.id!==j.dataset.id));renderJobs()}});
let deferredPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBox').classList.add('show')});$('installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBox').classList.remove('show')});window.addEventListener('appinstalled',()=>$('installBox').classList.remove('show'));if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
loadPricing();resetJob();renderJobs();
})();
